python main.py --model deeplabv3plus_resnet101\
       	--dataset cityscapes\
       	--lr 0.01\
       	--crop_size 768\
       	--batch_size 16\
       	--output_stride 16\
       	--data_root /opt/cloudroot/datasets/cityscapes\
       	--gpu_id 2,3\
       	--run_name VANILLA-CARLAT12_FT_Cityscapes_0.01\
       	--ckpt checkpoints/vanilla-carlat12_best_0.820740_iter20500_deeplabv3plus_resnet101_carla_os16.pth \
       	--wandb
